import ballerinax/microsoft.teams;
import ballerina/http;

# A service representing a network-accessible API
# bound to port `9090`.
service / on new http:Listener(9090) {

    # A resource for generating greetings
    # + return - string name with hello message or error
    resource function get api() returns json|error {
        // Send a response back to the caller.

        teams:Client teamsEndpoint = check new ({auth: {token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyIsImtpZCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyJ9.eyJhdWQiOiJlZTc0YzU0Ni0wNDI2LTQyM2ItOWUxMi1jNTdmNjRjMjYzOTMiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hNDhiYzZjNS1kZGZhLTRjMjYtYmYyOC00OTBlMDJkMzAxNzcvIiwiaWF0IjoxNjU0MDAzNzU2LCJuYmYiOjE2NTQwMDM3NTYsImV4cCI6MTY1NDAwNzkwOCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhUQUFBQU4wWTh4NTFYTHBYNkFYR0lKZkJmYlRmVGlRbzYwVDhYNHNuUGRjWGVEOFpKZWJSUmJTUEZTTkFSVHg4NnFuR0Z0TE02Q0FWU2p6YVl6NXZNMnFRMTFGSFlzOVQxaUxuQlBZNGIzdDhQTUlRPSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiJlZTc0YzU0Ni0wNDI2LTQyM2ItOWUxMi1jNTdmNjRjMjYzOTMiLCJhcHBpZGFjciI6IjEiLCJlbWFpbCI6Im9ydWtvb2d1dHVAb3V0bG9vay5jb20iLCJmYW1pbHlfbmFtZSI6Ik9ndXR1IiwiZ2l2ZW5fbmFtZSI6Ik9rb3RoIiwiaWRwIjoibGl2ZS5jb20iLCJpcGFkZHIiOiI0MS4yMTIuMTIxLjg1IiwibmFtZSI6Ik9rb3RoIE9ndXR1Iiwib2lkIjoiYmM0NTQ1OGMtNjlkNS00YjQ1LWE2YjUtYjEzNTg3NmZlNTBiIiwicmgiOiIwLkFVZ0F4Y2FMcFByZEpreV9LRWtPQXRNQmQwYkZkTzRtQkR0Q25oTEZmMlRDWTVOSUFLSS4iLCJzY3AiOiJVc2VyLlJlYWQiLCJzdWIiOiJLZUYzQXhoUnFFNnlSMjNYek54UTJ5YzVkMFdNcWk3dXZJaG4yZHU0YnFnIiwidGlkIjoiYTQ4YmM2YzUtZGRmYS00YzI2LWJmMjgtNDkwZTAyZDMwMTc3IiwidW5pcXVlX25hbWUiOiJsaXZlLmNvbSNvcnVrb29ndXR1QG91dGxvb2suY29tIiwidXRpIjoiZ3lidHFXSmhGVWl5M20yQ3c2VnJBQSIsInZlciI6IjEuMCJ9.PCUXJUEftB6yTlHAi_ZN76t6LMqXNjE9Rns7T_FrWJtNKT77LlocprqZKSH-F9m50tkzZiV9KrMI270OsAiniveq-oWZKLel-N9vrOURxP5WXwjJTczX1BYhZxK9e0gsWtKtNOnPjhB7ZdXDJ9I4Cwhh8W5e_zIV9EU5uYWYs0AacnbTp30pNCQZOpXevVoIKx8cK_Qwpy_FUreTtiaHjHEQaQKNZNx1x372_TfIamNIHRz_Gl4kI_nGJVE5kqnYFv-FXcaXNb9impSLAfEexHCNJIBzbd7mXNvnGjuI1sMsOAV7lJdqXG4o5JhmMVM9GzEvzSobJF9HWL8mwAQkdA"}});
        string createTeamResponse = check teamsEndpoint->createTeam({displayName: "School Meeting", description: "Discussing current issues", classification: "", specialization: "educationClass", visibility: "public", isArchived: false});
        return createTeamResponse.toJson();
    }
}
