import ballerinax/microsoft.teams;
import ballerina/http;

# A service representing a network-accessible API
# bound to port `9090`.
service / on new http:Listener(9090) {

    # A resource for generating greetings
    # + return - string name with hello message or error
    resource function get api() returns json|error {
        // Send a response back to the caller.

        teams:Client teamsEndpoint = check new ({auth: {token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyIsImtpZCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyJ9.eyJhdWQiOiJlZTc0YzU0Ni0wNDI2LTQyM2ItOWUxMi1jNTdmNjRjMjYzOTMiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hNDhiYzZjNS1kZGZhLTRjMjYtYmYyOC00OTBlMDJkMzAxNzcvIiwiaWF0IjoxNjUzOTgzMjg0LCJuYmYiOjE2NTM5ODMyODQsImV4cCI6MTY1Mzk4ODI3MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhUQUFBQXptaGlYQXc4aGhtZ1AreWlDZjRUUHpzSnRGejErSmR3TVhFZnVkWEtXOXdscTJGWWx3L1grWVFYVVJVZVNEVW5qZVJtSXNjV25QWFRXUnhsWmVFdVpQbW5WZW9mZ1ZEOGx5OFNYckJRYjVrPSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiJlZTc0YzU0Ni0wNDI2LTQyM2ItOWUxMi1jNTdmNjRjMjYzOTMiLCJhcHBpZGFjciI6IjEiLCJlbWFpbCI6Im9ydWtvb2d1dHVAb3V0bG9vay5jb20iLCJmYW1pbHlfbmFtZSI6Ik9ndXR1IiwiZ2l2ZW5fbmFtZSI6Ik9rb3RoIiwiaWRwIjoibGl2ZS5jb20iLCJpcGFkZHIiOiI0MS4yMTIuMTIxLjg1IiwibmFtZSI6Ik9rb3RoIE9ndXR1Iiwib2lkIjoiYmM0NTQ1OGMtNjlkNS00YjQ1LWE2YjUtYjEzNTg3NmZlNTBiIiwicmgiOiIwLkFVZ0F4Y2FMcFByZEpreV9LRWtPQXRNQmQwYkZkTzRtQkR0Q25oTEZmMlRDWTVOSUFLSS4iLCJzY3AiOiJVc2VyLlJlYWQiLCJzdWIiOiJLZUYzQXhoUnFFNnlSMjNYek54UTJ5YzVkMFdNcWk3dXZJaG4yZHU0YnFnIiwidGlkIjoiYTQ4YmM2YzUtZGRmYS00YzI2LWJmMjgtNDkwZTAyZDMwMTc3IiwidW5pcXVlX25hbWUiOiJsaXZlLmNvbSNvcnVrb29ndXR1QG91dGxvb2suY29tIiwidXRpIjoiVTJQLUxWajM0RXVjNHpGVkxPRnFBQSIsInZlciI6IjEuMCJ9.ZzxgdocL4wCfrb6E0odm_8SH1SR8y0vkdympVY1P8GyECkBujeLlXJqJJ4Iz5_0pJIjVmldYUXPyxnchXXmpM-sirF0me07xQzRIs-VjiTDH5XGyFt69sdfs6bpM2djKblXFq6EqCfZHlPv-fRn-n3pXmPPlECjil_yf5TDZN3KM2MbkF5dLHZYxPk2VI2O9Jrk6R3c8dljWO9hpKNws14Frl8ifk9hdAkYeN-TWXxNxSVz3gLI7bcCwM4Kk9R5OAwsaVI31Q36yFqWgu_nfuhlECE0mrTfJfUrHglWBLgxnmLdNMi5Ae-YilU2sHTIlzE8rhQWYHtpLF6rhxV6iAA"}});
        string createTeamResponse = check teamsEndpoint->createTeam({displayName: "School Meeting", description: "Discussing current issues", classification: "", specialization: "educationClass", visibility: "public", isArchived: false});
        return createTeamResponse.toJson();
    }
}
